<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE products [
<!ELEMENT product (part_number,name,url,description,category,brand,keywords,adult,variant)>
<!ELEMENT part_number (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT adult (#PCDATA)>
<!ELEMENT variants (sku,price,color,image,alternate_images)>
<!ELEMENT sku (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT alternate_images (#PCDATA)>
<!ENTITY Iacute "Í">
<!ENTITY iacute "í">
<!ENTITY frac12 "½">
<!ENTITY mdash "—">
<!ENTITY ndash "–">
<!ENTITY rsquo "’">
<!ENTITY rdquo "”">
<!ENTITY ldquo "“">
<!ENTITY lsquo "‘">
<!ENTITY eacute "é">
<!ENTITY Eacute "É">
<!ENTITY Uuml "Ü">
<!ENTITY auml "ä">
<!ENTITY ouml "ö">
<!ENTITY euml "ë">
<!ENTITY iuml "ï">
<!ENTITY uuml "ü">
<!ENTITY ordm "º">
<!ENTITY Ccedil "Ç">
<!ENTITY ccedil "ç">
<!ENTITY ucirc "û">
<!ENTITY Ucirc "Û">
<!ENTITY Ograve "Ò">
<!ENTITY reg "®">
<!ENTITY oslash "ø">
<!ENTITY Oslash "Ø">
<!ENTITY trade "">
]>

<products>
  <product>
    <part_number>100000000000</part_number>
    <name>Wave Candlestick - Small</name>
    <url>http://store.dwell.com/wave-candlestick-small.html</url>
    <description>The Wave Candlestick combines traditional craft production with a contemporary design sensibility. Hand-turned by artisans in Jaipur, India and designed by Michael Dreeben for AKMD, the Wave Candlestick mimics the undulating curves of sine waves. Each candlestick is made from repurposed, sustainably-harvested Mango wood&mdash; a native tree to India&mdash; and is burned and oil finished. A weighted base secures its stability. Available in two sizes: small (12" height) and large (16" height). Sold individually.</description>
    <category>Home &gt; Decor &amp; Accessories &gt; Home Accents</category>
    <brand>AKMD</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100000000000</sku>
           <price>78</price>
           <color></color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/K/AKMD-WaveCandlestick-07.jpg.jpg</image>
           <alternate_images>http://store.dwell.com/media/catalog/product/A/K/AKMD-WaveCandlestick-06.jpg.jpg</alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100000000001</part_number>
    <name>Wave Candlestick - Large</name>
    <url>http://store.dwell.com/wave-candlestick-large.html</url>
    <description>The Wave Candlestick combines traditional craft production with a contemporary design sensibility. Hand-turned by artisans in Jaipur, India and designed by Michael Dreeben for AKMD, the Wave Candlestick mimics the undulating curves of sine waves. Each candlestick is made from repurposed, sustainably-harvested Mango wood&mdash; a native tree to India&mdash; and is burned and oil finished. A weighted base secures its stability. Available in two sizes: small (12" height) and large (16" height).  Sold individually.</description>
    <category>Home &gt; Decor &amp; Accessories &gt; Home Accents</category>
    <brand>AKMD</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100000000001</sku>
           <price>94</price>
           <color></color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/K/AKMD-WaveCandlestick-08.jpg.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000000</part_number>
    <name>VP1 FlowerPot Lamp - Yellow</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-yellow.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000000</sku>
           <price>380</price>
           <color>Yellow</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-vp1-yellow-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000001</part_number>
    <name>VP1 FlowerPot Lamp - White</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-white.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000001</sku>
           <price>380</price>
           <color>White</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-WHITE-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000002</part_number>
    <name>VP1 FlowerPot Lamp - Orange</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-orange.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000002</sku>
           <price>380</price>
           <color>orange</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-ORANGE-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000003</part_number>
    <name>VP1 FlowerPot Lamp - Red</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-red.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000003</sku>
           <price>380</price>
           <color>Red</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-RED-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000004</part_number>
    <name>VP1 FlowerPot Lamp - Turquoise</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-turquoise.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000004</sku>
           <price>380</price>
           <color>Turquoise</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-TURQUOISE-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000005</part_number>
    <name>VP1 FlowerPot Lamp - Stainless Steel</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-stainless-steel.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue, and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000005</sku>
           <price>450</price>
           <color>Stainless Steel</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-BRUSHED-trans.jpg_2.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000006</part_number>
    <name>VP1 FlowerPot Lamp - Black</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-black.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000006</sku>
           <price>380</price>
           <color>black</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-BLACK-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000007</part_number>
    <name>VP1 FlowerPot Lamp Light - Blue/Mint</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-light-blue-mint.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000007</sku>
           <price>380</price>
           <color>light blue-mint</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-MINT-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000008</part_number>
    <name>VP1 FlowerPot Lamp - Green</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-green.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000008</sku>
           <price>380</price>
           <color>green</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-GREEN-trans.jpg_2.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000009</part_number>
    <name>VP1 FlowerPot Lamp - Light Grey</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-light-grey.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000009</sku>
           <price>380</price>
           <color>light grey</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1_mattegrey.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100030000010</part_number>
    <name>VP1 FlowerPot Lamp - Blue</name>
    <url>http://store.dwell.com/vp1-flowerpot-lamp-blue.html</url>
    <description>Created by 20th-century Danish designer Verner Panton, the Flowerpot VP1 lamp is a stellar example of mid-century design. Designed in 1969, the ceiling-mount Flowerpot lamp takes its inspiration from the sunny '60s and is comprised of a pair of nesting spheres. A smaller sphere discreetly hides the bulb and is protected by the larger dome, both made from vibrant lacquered steel with a color-matched fabric cord. Available in yellow, white, orange, red, turquoise, green, light grey, black, blue, light blue and stainless steel.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100030000010</sku>
           <price>380</price>
           <color>blue</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP1-BLUE-trans.jpg_2.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100040000000</part_number>
    <name>VP4 Flowerpot Table Lamp - Yellow</name>
    <url>http://store.dwell.com/vp4-flowerpot-table-lamp-yellow.html</url>
    <description>Inspired by the spirit of the 1960s, Danish designer Verner Panton's Flowerpot VP4 Table Lamp is an testament to the enduring power of mid-century design. Its distinctive spherical shape telegraphs modernist style while precision engineering creates perfectly diffused light sure to brighten any room. Made of spun lacquered aluminum in vibrant shades of yellow, white, red, green black and chrome with matching fabric cords and chrome tubular supports.</description>
    <category>Home &gt; Lighting &gt; Table &amp; Desk Lamps</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100040000000</sku>
           <price>580</price>
           <color>Yellow</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-FlowerPotTableVP4Group.jpg_2.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100040000001</part_number>
    <name>VP4 Flowerpot Table Lamp - White</name>
    <url>http://store.dwell.com/vp4-flowerpot-table-lamp-white.html</url>
    <description>Inspired by the spirit of the 1960s, Danish designer Verner Panton's Flowerpot VP4 Table Lamp is an testament to the enduring power of mid-century design. Its distinctive spherical shape telegraphs modernist style while precision engineering creates perfectly diffused light sure to brighten any room. Made of spun lacquered aluminum in vibrant shades of yellow, white, red, green black and chrome with matching fabric cords and chrome tubular supports.</description>
    <category>Home &gt; Lighting &gt; Table &amp; Desk Lamps</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100040000001</sku>
           <price>580</price>
           <color>White</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-FlowerPotTableVP4Group.jpg_3.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100040000002</part_number>
    <name>VP4 Flowerpot Table Lamp - Red</name>
    <url>http://store.dwell.com/vp4-flowerpot-table-lamp-red.html</url>
    <description>Inspired by the spirit of the 1960s, Danish designer Verner Panton's Flowerpot VP4 Table Lamp is an testament to the enduring power of mid-century design. Its distinctive spherical shape telegraphs modernist style while precision engineering creates perfectly diffused light sure to brighten any room. Made of spun lacquered aluminum in vibrant shades of yellow, white, red, green black and chrome with matching fabric cords and chrome tubular supports.</description>
    <category>Home &gt; Lighting &gt; Table &amp; Desk Lamps</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100040000002</sku>
           <price>580</price>
           <color>Red</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-FlowerPotTableVP4Group.jpg_4.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100040000003</part_number>
    <name>VP4 Flowerpot Table Lamp - Green</name>
    <url>http://store.dwell.com/vp4-flowerpot-table-lamp-green.html</url>
    <description>Inspired by the spirit of the 1960s, Danish designer Verner Panton's Flowerpot VP4 Table Lamp is an testament to the enduring power of mid-century design. Its distinctive spherical shape telegraphs modernist style while precision engineering creates perfectly diffused light sure to brighten any room. Made of spun lacquered aluminum in vibrant shades of yellow, white, red, green black and chrome with matching fabric cords and chrome tubular supports.</description>
    <category>Home &gt; Lighting &gt; Table &amp; Desk Lamps</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100040000003</sku>
           <price>580</price>
           <color>green</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP4-GREEN-trans.jpg_2.jpg</image>
           <alternate_images>http://store.dwell.com/media/catalog/product/A/m/Ameico-FlowerPotTableVP4Group.jpg_5.jpg</alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100040000004</part_number>
    <name>VP4 Flowerpot Table Lamp - Black</name>
    <url>http://store.dwell.com/vp4-flowerpot-table-lamp-black.html</url>
    <description>Inspired by the spirit of the 1960s, Danish designer Verner Panton's Flowerpot VP4 Table Lamp is an testament to the enduring power of mid-century design. Its distinctive spherical shape telegraphs modernist style while precision engineering creates perfectly diffused light sure to brighten any room. Made of spun lacquered aluminum in vibrant shades of yellow, white, red, green black and chrome with matching fabric cords and chrome tubular supports.</description>
    <category>Home &gt; Lighting &gt; Table &amp; Desk Lamps</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100040000004</sku>
           <price>580</price>
           <color>black</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-FlowerPotTableVP4Group.jpg_6.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100040000005</part_number>
    <name>VP4 Flowerpot Table Lamp - Chrome</name>
    <url>http://store.dwell.com/vp4-flowerpot-table-lamp-chrome.html</url>
    <description>Inspired by the spirit of the 1960s, Danish designer Verner Panton's Flowerpot VP4 Table Lamp is an testament to the enduring power of mid-century design. Its distinctive spherical shape telegraphs modernist style while precision engineering creates perfectly diffused light sure to brighten any room. Made of spun lacquered aluminum in vibrant shades of yellow, white, red, green black and chrome with matching fabric cords and chrome tubular supports.</description>
    <category>Home &gt; Lighting &gt; Table &amp; Desk Lamps</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100040000005</sku>
           <price>700</price>
           <color>chrome</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-vp4-chrome-trans.jpg_2.jpg</image>
           <alternate_images>http://store.dwell.com/media/catalog/product/A/m/Ameico-FlowerPotTableVP4Group.jpg_7.jpg</alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100050000000</part_number>
    <name>VP6 Topan Pendant Light - Yellow</name>
    <url>http://store.dwell.com/vp6-topan-pendant-light-yellow.html</url>
    <description>Originally designed for Norway's Astoria restaurant and hotel in Trondheim, the Topan VP6 lamp is the first mass-produced lamp created by mid-century Danish designer Verner Panton. This simple ceiling-mount lamp evokes the design values of the early 1960s with clean lines and bold color variations. Made from spun aluminum with a glossy lacquered finish and color-coordinated fabric cord. Provides both direct and ambient light.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100050000000</sku>
           <price>360</price>
           <color>Yellow</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP6-YELLOW-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100050000001</part_number>
    <name>VP6 Topan Pendant Light - White</name>
    <url>http://store.dwell.com/vp6-topan-pendant-light-white.html</url>
    <description>Originally designed for Norway's Astoria restaurant and hotel in Trondheim, the Topan VP6 lamp is the first mass-produced lamp created by mid-century Danish designer Verner Panton. This simple ceiling-mount lamp evokes the design values of the early 1960s with clean lines and bold color variations. Made from spun aluminum with a glossy lacquered finish and color-coordinated fabric cord. Provides both direct and ambient light.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100050000001</sku>
           <price>360</price>
           <color>White</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP6-WHITE-trans.jpg_1.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
<product>
    <part_number>100050000002</part_number>
    <name>VP6 Topan Pendant Light - Orange</name>
    <url>http://store.dwell.com/vp6-topan-pendant-light-orange.html</url>
    <description>Originally designed for Norway's Astoria restaurant and hotel in Trondheim, the Topan VP6 lamp is the first mass-produced lamp created by mid-century Danish designer Verner Panton. This simple ceiling-mount lamp evokes the design values of the early 1960s with clean lines and bold color variations. Made from spun aluminum with a glossy lacquered finish and color-coordinated fabric cord. Provides both direct and ambient light.</description>
    <category>Home &gt; Lighting &gt; Ceiling</category>
    <brand>&amp; Tradition</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100050000002</sku>
           <price>360</price>
           <color>orange</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-VP6-ORANGE-trans.jpg_2.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>