<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE products [
<!ELEMENT product (part_number,name,url,description,category,brand,keywords,adult,variant)>
<!ELEMENT part_number (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT adult (#PCDATA)>
<!ELEMENT variants (sku,price,color,image,alternate_images)>
<!ELEMENT sku (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT alternate_images (#PCDATA)>
<!ENTITY Iacute "Í">
<!ENTITY iacute "í">
<!ENTITY frac12 "½">
<!ENTITY mdash "—">
<!ENTITY ndash "–">
<!ENTITY rsquo "’">
<!ENTITY rdquo "”">
<!ENTITY ldquo "“">
<!ENTITY lsquo "‘">
<!ENTITY eacute "é">
<!ENTITY Eacute "É">
<!ENTITY Uuml "Ü">
<!ENTITY auml "ä">
<!ENTITY ouml "ö">
<!ENTITY euml "ë">
<!ENTITY iuml "ï">
<!ENTITY uuml "ü">
<!ENTITY ordm "º">
<!ENTITY Ccedil "Ç">
<!ENTITY ccedil "ç">
<!ENTITY ucirc "û">
<!ENTITY Ucirc "Û">
<!ENTITY Ograve "Ò">
<!ENTITY reg "®">
<!ENTITY oslash "ø">
<!ENTITY Oslash "Ø">
<!ENTITY trade "">
<!ENTITY gt ">">
<!ENTITY amp "&#038;">
]>


<products>
  <product>
    <part_number>88</part_number>
    <name>Smal Pug XML</name>
    <url>http://afilliate.com/product/1234-5678</url>
    <description>his is a tiny little pug. From XML.</description>
    <category>Home &gt; Outdoor</category>
    <brand>Kitten brand</brand>
    <keywords>cat, pet, tan, xml</keywords>
    <variants>
      <sku>1</sku>
      <price>50.00</price>
      <inventory>10</inventory>
      <sale_price>40.00</sale_price>
      <color>Tan</color>
      <size>Small</size>
      <image>http://placekitten.com/900/900</image>
      <alternate_images>http://placekitten.com/900/700</alternate_images>
    </variants>
    <variants>
      <sku>2</sku>
      <price>50.00</price>
      <sale_price>40.00</sale_price>
      <color>Tan</color>
      <size>Large</size>
      <image>http://27.media.tumblr.com/tumblr_ls6tpnEwe71r3ip8io1_500.jpg</image>
      <alternate_images>http://25.media.tumblr.com/tumblr_lm1gf8IEiu1qko977o1_500.jpg</alternate_images>
    </variants>
  </product>
  <product>
    <part_number>99</part_number>
    <name>Soy candle</name>
    <url>http://afilliate.com/product/1234-0001</url>
    <description>Blah blah blah.</description>
    <category>Home &gt; Decor &amp; Accessories &gt; Home Accents</category>
    <brand>Joe&apos;s Candles</brand>
    <keywords>soy, organic, aromatherapy</keywords>
    <variants>
      <sku>1234-0001-sandalwood</sku>
      <price>20.00</price>
      <material>100&#37; Soy</material>
      <image>http://placekitten.com/700/1000</image>
    </variants>
  </product>
<product>
    <part_number>100250000000</part_number>
    <name>Peter Maly Two-Piece Andirons</name>
    <url>http://store.dwell.com/peter-maly-two-piece-andirons.html</url>
    <description>&ldquo;I like working with clear, geometric forms: for me, they are the essential condition of their longevity,&rdquo; notes designer Peter Maly. In his two-piece set of andirons, his sentiment is made visible. Distilling the form to its most fundamental, Peter Maly&rsquo;s andirons are minimal and clean. Made in Germany from stainless steel.</description>
    <category>Home &gt; Decor &amp; Accessories &gt; Home Accents</category>
    <brand>Conmoto</brand>
    <keywords></keywords>
    <adult>false</adult>
       <variants>
           <sku>100250000000</sku>
           <price>850</price>
           <color>stainless steel, matte</color>
           <image>http://store.dwell.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/A/m/Ameico-Peter-Maly-2-piece-andiron-01.jpg.jpg</image>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
           <alternate_images></alternate_images>
       </variants>
    </product>
</products>